# Generated by Django 5.2 on 2025-04-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_serie', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('horimetro_atual', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ultima_manutencao_horimetro', models.CharField(max_length=100)),
                ('data_ultima_manutencao', models.DateField()),
            ],
        ),
    ]
